# Generated by Django 6.1 on 2026-08-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('endereco', models.TextField(blank=True, verbose_name='endereço')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['nome_completo'],
            },
        ),
    ]
