# Generated by Django 6.1 on 2026-09-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paciente_convenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data do atendimento')),
                ('descricao', models.TextField(verbose_name='descricao do procedimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='core.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'evolucao',
                'verbose_name_plural': 'evolucoes',
                'ordering': ['data'],
            },
        ),
    ]
