# Generated by Django 6.1 on 2026-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=18, unique=True, verbose_name='CPF'),
        ),
    ]
