# Generated by Django 6.1 on 2026-09-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paciente_cpf_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('hora_inicio', models.TimeField(verbose_name='hora início')),
                ('hora_fim', models.TimeField(verbose_name='hora fim')),
                ('status', models.CharField(choices=[('agendada', 'agendada'), ('realizada', 'realizada'), ('faltou', 'faltou'), ('cancelada', 'cancelada')], default='agendada', max_length=20, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='core.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'consulta',
                'verbose_name_plural': 'consultas',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
    ]
