# Generated by Django 6.1 on 2026-09-04 17:06

from django.db import migrations, models


def criar_convenio_particular(apps, schema_editor):
    Convenio = apps.get_model('core', 'Convenio')
    Paciente = apps.get_model('core', 'Paciente')
    particular, _ = Convenio.objects.get_or_create(
        nome='Particular',
        defaults={'ativo': True},
    )
    Paciente.objects.filter(convenio__isnull=True).update(convenio=particular)


def remover_convenio_particular(apps, schema_editor):
    Convenio = apps.get_model('core', 'Convenio')
    Paciente = apps.get_model('core', 'Paciente')
    particular = Convenio.objects.filter(nome='Particular').first()
    if particular:
        Paciente.objects.filter(convenio=particular).update(convenio=None)
        particular.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='pago'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='percentual_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='percentual de desconto'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='percentual_imposto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='percentual de imposto'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor da hora'),
        ),
        migrations.RunPython(criar_convenio_particular, remover_convenio_particular),
    ]
