# Generated by Django 6.1 on 2026-09-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_convenio_tabela_consulta_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'dinheiro'), ('cartao_credito', 'cartão de crédito'), ('pix', 'pix'), ('outros', 'outros')], default='', max_length=20, verbose_name='forma de pagamento'),
        ),
    ]
