# Generated by Django 6.1 on 2026-09-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_consulta_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='core.consulta', verbose_name='consulta')),
            ],
            options={
                'verbose_name': 'material usado',
                'verbose_name_plural': 'materiais usados',
                'ordering': ['descricao'],
            },
        ),
    ]
