# Generated by Django 6.1 on 2026-09-07 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_materialusado'),
        ('locacao', '0008_procedimentos_lancamentos_legado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='locacao.dentista', verbose_name='dentista'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='dentista_complementado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dentista complementado em'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='dentista_complementado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas_dentista_complementadas', to=settings.AUTH_USER_MODEL, verbose_name='dentista complementado por'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='eh_legado',
            field=models.BooleanField(default=False, verbose_name='registro legado'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='valor_historico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor histórico congelado'),
        ),
        migrations.CreateModel(
            name='AuditoriaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='descrição')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='core.consulta', verbose_name='consulta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_consulta', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'auditoria de consulta',
                'verbose_name_plural': 'auditorias de consulta',
                'ordering': ['-cadastrado_em'],
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('duracao_estimada_minutos', models.PositiveIntegerField(blank=True, null=True, verbose_name='duração estimada (minutos)')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos', to='locacao.dentista', verbose_name='dentista')),
            ],
            options={
                'verbose_name': 'procedimento',
                'verbose_name_plural': 'procedimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PrecoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('convenio', models.ForeignKey(blank=True, help_text='Vazio = tabela particular.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='precos_procedimento', to='core.convenio', verbose_name='convênio')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='core.procedimento', verbose_name='procedimento')),
            ],
            options={
                'verbose_name': 'preço de procedimento',
                'verbose_name_plural': 'preços de procedimento',
            },
        ),
        migrations.CreateModel(
            name='LancamentoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_procedimento', models.CharField(max_length=200, verbose_name='procedimento')),
                ('particular', models.BooleanField(default=True, verbose_name='tabela particular')),
                ('valor_tabela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor de tabela')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='desconto aplicado (%)')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor final')),
                ('tipo', models.CharField(choices=[('atendimento', 'atendimento'), ('ajuste', 'ajuste')], default='atendimento', max_length=20, verbose_name='tipo')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='data do lançamento')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_atendimento', to=settings.AUTH_USER_MODEL, verbose_name='lançado por')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='core.consulta', verbose_name='consulta')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_atendimento', to='core.convenio', verbose_name='tabela convênio')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_atendimento', to='locacao.dentista', verbose_name='dentista')),
                ('procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='core.procedimento', verbose_name='procedimento do catálogo')),
            ],
            options={
                'verbose_name': 'lançamento de atendimento',
                'verbose_name_plural': 'lançamentos de atendimento',
                'ordering': ['cadastrado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='procedimento',
            constraint=models.UniqueConstraint(fields=('dentista', 'nome'), name='procedimento_unico_por_dentista'),
        ),
        migrations.AddConstraint(
            model_name='precoprocedimento',
            constraint=models.UniqueConstraint(fields=('procedimento', 'convenio'), name='preco_unico_procedimento_tabela', nulls_distinct=False),
        ),
    ]
