# Generated by Django 6.1 on 2026-09-07 19:43

from decimal import Decimal
from django.db import migrations, models


def popular_tabela_uniodonto(apps, schema_editor):
    from core.tabela_uniodonto import popular_convenio_e_tabela

    Convenio = apps.get_model('core', 'Convenio')
    ProcedimentoUniodonto = apps.get_model('core', 'ProcedimentoUniodonto')
    popular_convenio_e_tabela(Convenio, ProcedimentoUniodonto)


def esvaziar_tabela_uniodonto(apps, schema_editor):
    Convenio = apps.get_model('core', 'Convenio')
    ProcedimentoUniodonto = apps.get_model('core', 'ProcedimentoUniodonto')
    ProcedimentoUniodonto.objects.all().delete()
    Convenio.objects.filter(nome='Uniodonto').update(usa_tabela_oficial=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_congelar_consultas_legado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoUniodonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código TUSS')),
                ('nome', models.CharField(max_length=300, verbose_name='nome')),
                ('categoria', models.CharField(choices=[('nao_classificada', 'Não classificada'), ('dentistica', 'Dentística'), ('endodontia', 'Endodontia'), ('periodontia', 'Periodontia')], default='nao_classificada', max_length=32, verbose_name='categoria')),
                ('valor_us', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor US')),
                ('valor_reais', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor R$')),
                ('fator_us', models.DecimalField(decimal_places=4, default=Decimal('0.1712'), max_digits=8, verbose_name='fator US')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'procedimento Uniodonto',
                'verbose_name_plural': 'procedimentos Uniodonto',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='convenio',
            name='usa_tabela_oficial',
            field=models.BooleanField(default=False, help_text='Uniodonto: preços vêm da tabela compartilhada, não do catálogo da dentista.', verbose_name='usa tabela oficial da cooperativa'),
        ),
        migrations.RunPython(popular_tabela_uniodonto, esvaziar_tabela_uniodonto),
    ]
