# Generated by Django 6.1 on 2026-09-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tabela_uniodonto_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoatendimento',
            name='codigo_tuss',
            field=models.CharField(blank=True, max_length=20, verbose_name='código TUSS'),
        ),
        migrations.AddField(
            model_name='lancamentoatendimento',
            name='fator_us',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='fator US'),
        ),
        migrations.AddField(
            model_name='lancamentoatendimento',
            name='procedimento_uniodonto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='core.procedimentouniodonto', verbose_name='procedimento Uniodonto'),
        ),
        migrations.AddField(
            model_name='lancamentoatendimento',
            name='valor_us',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor US'),
        ),
        migrations.AlterField(
            model_name='lancamentoatendimento',
            name='nome_procedimento',
            field=models.CharField(max_length=300, verbose_name='procedimento'),
        ),
    ]
