# Generated by Django 6.1 on 2026-09-07 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lancamento_uniodonto_ficha'),
        ('locacao', '0008_procedimentos_lancamentos_legado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepasseUniodonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Primeiro dia do mês.', verbose_name='competência')),
                ('producao_bruta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='produção bruta')),
                ('glosa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='glosa')),
                ('estorno', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='estorno')),
                ('inss_retido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='INSS retido')),
                ('irrf_retido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IRRF retido')),
                ('liquido_recebido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='líquido recebido')),
                ('liquido_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='líquido calculado')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repasses_uniodonto', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repasses_uniodonto', to='locacao.dentista', verbose_name='dentista')),
            ],
            options={
                'verbose_name': 'repasse Uniodonto',
                'verbose_name_plural': 'repasses Uniodonto',
                'ordering': ['-competencia', 'dentista'],
                'constraints': [models.UniqueConstraint(fields=('dentista', 'competencia'), name='repasse_uniodonto_dentista_competencia_unico')],
            },
        ),
    ]
