# Generated by Django 6.1 on 2026-09-07 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_repasse_uniodonto_mensal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaEletronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('componente_teste', 'componente de teste'), ('evolucao', 'evolução'), ('plano_tratamento', 'plano de tratamento / consentimento'), ('anamnese', 'cadastro / anamnese'), ('autorizacao_custo', 'autorização de itens com custo')], max_length=40, verbose_name='tipo do documento')),
                ('documento_id', models.PositiveIntegerField(default=0, verbose_name='id do documento')),
                ('papel', models.CharField(choices=[('paciente', 'paciente'), ('dentista', 'dentista'), ('responsavel', 'responsável'), ('testemunha', 'testemunha')], max_length=20, verbose_name='papel')),
                ('tipo_assinatura', models.CharField(choices=[('manuscrita', 'manuscrita'), ('icp_brasil', 'ICP-Brasil')], default='manuscrita', max_length=20, verbose_name='tipo de assinatura')),
                ('imagem', models.FileField(blank=True, upload_to='assinaturas/%Y/%m/', verbose_name='imagem da assinatura')),
                ('nome_assinante', models.CharField(max_length=200, verbose_name='nome de quem assinou')),
                ('cpf_assinante', models.CharField(blank=True, max_length=18, verbose_name='CPF de quem assinou')),
                ('assinado_em', models.DateTimeField(auto_now_add=True, verbose_name='assinado em')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='user agent')),
                ('hash_conteudo', models.CharField(blank=True, max_length=64, verbose_name='hash do conteúdo')),
                ('hash_imagem', models.CharField(blank=True, max_length=64, verbose_name='hash da imagem')),
                ('certificado_id', models.CharField(blank=True, max_length=120, verbose_name='id do certificado')),
                ('certificado_serial', models.CharField(blank=True, max_length=120, verbose_name='serial do certificado')),
                ('certificado_emissor', models.CharField(blank=True, max_length=200, verbose_name='emissor do certificado')),
                ('validade_certificado_inicio', models.DateTimeField(blank=True, null=True, verbose_name='início da validade do certificado')),
                ('validade_certificado_fim', models.DateTimeField(blank=True, null=True, verbose_name='fim da validade do certificado')),
                ('politica', models.CharField(blank=True, max_length=40, verbose_name='política (CAdES/PAdES)')),
                ('pacote_assinatura', models.BinaryField(blank=True, null=True, verbose_name='pacote CMS/PAdES')),
                ('carimbo_tempo', models.DateTimeField(blank=True, null=True, verbose_name='carimbo de tempo')),
                ('status_verificacao', models.CharField(choices=[('nao_aplicavel', 'não aplicável'), ('valida', 'válida'), ('invalida', 'inválida'), ('expirada', 'expirada')], default='nao_aplicavel', max_length=20, verbose_name='status da verificação')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas', to='core.paciente', verbose_name='paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_coletadas', to=settings.AUTH_USER_MODEL, verbose_name='usuário logado')),
            ],
            options={
                'verbose_name': 'assinatura eletrônica',
                'verbose_name_plural': 'assinaturas eletrônicas',
                'ordering': ['-assinado_em'],
            },
        ),
    ]
