# Generated by Django 6.1 on 2026-09-07 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_assinatura_eletronica'),
        ('locacao', '0008_procedimentos_lancamentos_legado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaCadastroAnamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'rascunho'), ('aguardando_dentista', 'aguardando dentista'), ('concluida', 'concluída')], default='rascunho', max_length=30, verbose_name='status')),
                ('preenchida_por', models.CharField(choices=[('paciente', 'paciente'), ('equipe', 'equipe')], default='equipe', max_length=20, verbose_name='preenchida por')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token do link')),
                ('token_expira_em', models.DateTimeField(verbose_name='link expira em')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='nome completo')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('cpf', models.CharField(max_length=18, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('endereco', models.TextField(blank=True, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('profissao', models.CharField(blank=True, max_length=120, verbose_name='profissão')),
                ('nome_responsavel', models.CharField(blank=True, max_length=200, verbose_name='responsável legal')),
                ('saude_condicoes', models.JSONField(blank=True, default=list, verbose_name='sua saúde')),
                ('saude_outra_texto', models.CharField(blank=True, max_length=200, verbose_name='outra condição de saúde')),
                ('alergia', models.CharField(blank=True, choices=[('sim', 'sim'), ('nao', 'não')], default='', max_length=20, verbose_name='alergia a medicamentos, alimentos ou látex')),
                ('alergia_qual', models.CharField(blank=True, max_length=200, verbose_name='qual alergia')),
                ('usa_medicamento', models.CharField(blank=True, choices=[('sim', 'sim'), ('nao', 'não')], default='', max_length=20, verbose_name='usa medicamento')),
                ('medicamento_nome', models.CharField(blank=True, max_length=200, verbose_name='nome do medicamento')),
                ('cirurgia_recente', models.CharField(blank=True, choices=[('sim', 'sim'), ('nao', 'não')], default='', max_length=20, verbose_name='cirurgia ou internação recente')),
                ('cirurgia_qual', models.CharField(blank=True, max_length=200, verbose_name='qual cirurgia ou internação / quando')),
                ('saude_bucal', models.JSONField(blank=True, default=list, verbose_name='sua saúde bucal')),
                ('data_ultima_consulta', models.DateField(blank=True, null=True, verbose_name='data da última consulta odontológica')),
                ('experiencia_anterior', models.CharField(blank=True, choices=[('sim', 'sim'), ('nao', 'não')], default='', max_length=20, verbose_name='experiência odontológica anterior')),
                ('experiencia_relato', models.TextField(blank=True, verbose_name='relato da experiência anterior')),
                ('o_que_incomoda', models.TextField(blank=True, verbose_name='o que mais incomoda')),
                ('o_que_espera', models.TextField(blank=True, verbose_name='o que espera do tratamento')),
                ('fuma', models.CharField(blank=True, choices=[('sim', 'sim'), ('nao', 'não')], default='', max_length=20, verbose_name='fuma / nicotina')),
                ('bebida_alcoolica', models.CharField(blank=True, choices=[('sim', 'sim'), ('nao', 'não')], default='', max_length=20, verbose_name='bebida alcoólica')),
                ('range_dentes', models.CharField(blank=True, choices=[('sim', 'sim'), ('nao', 'não'), ('nao_sei', 'não sei')], default='', max_length=20, verbose_name='range ou aperta os dentes')),
                ('gravidez', models.CharField(blank=True, choices=[('sim', 'sim'), ('nao', 'não'), ('nao_se_aplica', 'não se aplica')], default='', max_length=20, verbose_name='grávida ou possibilidade de gravidez')),
                ('outra_info_saude', models.CharField(blank=True, choices=[('sim', 'sim'), ('nao', 'não')], default='', max_length=20, verbose_name='outra informação de saúde relevante')),
                ('outra_info_relato', models.TextField(blank=True, verbose_name='relato de outra informação de saúde')),
                ('aceitou_declaracao', models.BooleanField(default=False, verbose_name='aceitou a declaração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_anamnese_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('dentista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_anamnese', to='locacao.dentista', verbose_name='dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_anamnese', to='core.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'ficha de cadastro e anamnese',
                'verbose_name_plural': 'fichas de cadastro e anamnese',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['rascunho', 'aguardando_dentista'])), fields=('paciente',), name='uma_ficha_anamnese_aberta_por_paciente')],
            },
        ),
    ]
