# Generated by Django 6.1 on 2026-09-08 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ficha_cadastro_anamnese'),
        ('locacao', '0008_procedimentos_lancamentos_legado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEvolucaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('procedimento_etapa', models.CharField(max_length=200, verbose_name='procedimento / etapa realizada')),
                ('descricao_clinica', models.TextField(verbose_name='descrição clínica / conduta')),
                ('orientacoes', models.TextField(blank=True, verbose_name='orientações fornecidas')),
                ('nome_profissional', models.CharField(max_length=200, verbose_name='profissional')),
                ('cro', models.CharField(max_length=30, verbose_name='CRO')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_evolucao_clinica_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('dentista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_evolucao_clinica', to='locacao.dentista', verbose_name='dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_evolucao_clinica', to='core.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'registro de evolução clínica',
                'verbose_name_plural': 'registros de evolução clínica',
                'ordering': ['data', 'criado_em', 'pk'],
            },
        ),
    ]
