# Generated by Django 6.1 on 2026-09-08 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_registro_evolucao_clinica'),
        ('locacao', '0008_procedimentos_lancamentos_legado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='facebook',
            field=models.CharField(blank=True, max_length=120, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='instagram',
            field=models.CharField(blank=True, max_length=120, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='outra_rede_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='outra rede social'),
        ),
        migrations.AlterField(
            model_name='assinaturaeletronica',
            name='tipo_documento',
            field=models.CharField(choices=[('componente_teste', 'componente de teste'), ('evolucao', 'evolução'), ('plano_tratamento', 'plano de tratamento / consentimento'), ('plano_procedimento', 'consentimento por procedimento'), ('plano_profissional', 'assinatura profissional do plano'), ('anamnese', 'cadastro / anamnese'), ('autorizacao_custo', 'autorização de itens com custo')], max_length=40, verbose_name='tipo do documento'),
        ),
        migrations.CreateModel(
            name='FichaPlanoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'rascunho'), ('concluida', 'concluída')], default='rascunho', max_length=20, verbose_name='status')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='nome completo')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('cpf', models.CharField(max_length=18, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('endereco', models.TextField(blank=True, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('profissao', models.CharField(blank=True, max_length=120, verbose_name='profissão')),
                ('nome_responsavel', models.CharField(blank=True, max_length=200, verbose_name='responsável legal')),
                ('plano_tratamento', models.TextField(blank=True, verbose_name='plano de tratamento')),
                ('ciencia_itens', models.JSONField(blank=True, default=list, verbose_name='itens de ciência informados')),
                ('aceitou_declaracao', models.BooleanField(default=False, verbose_name='aceitou a declaração')),
                ('local_assinatura', models.CharField(blank=True, max_length=120, verbose_name='local')),
                ('data_consentimento', models.DateField(blank=True, null=True, verbose_name='data do consentimento')),
                ('complexidade_itens', models.JSONField(blank=True, default=list, verbose_name='procedimentos de maior complexidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_plano_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_plano', to='core.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'ficha de plano e consentimento',
                'verbose_name_plural': 'fichas de plano e consentimento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemConsentimentoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('procedimento', models.CharField(max_length=200, verbose_name='procedimento')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('cro', models.CharField(blank=True, max_length=80, verbose_name='CRO')),
                ('dentistas', models.ManyToManyField(blank=True, related_name='itens_consentimento_plano', to='locacao.dentista', verbose_name='dentistas responsáveis')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.fichaplanotratamento', verbose_name='ficha')),
            ],
            options={
                'verbose_name': 'item de consentimento de procedimento',
                'verbose_name_plural': 'itens de consentimento de procedimento',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ResponsavelPlanoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('nome', models.CharField(max_length=200, verbose_name='profissional')),
                ('cro', models.CharField(max_length=80, verbose_name='CRO')),
                ('dentista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_plano', to='locacao.dentista', verbose_name='dentista')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='core.fichaplanotratamento', verbose_name='ficha')),
            ],
            options={
                'verbose_name': 'profissional do plano',
                'verbose_name_plural': 'profissionais do plano',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='fichaplanotratamento',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rascunho')), fields=('paciente',), name='uma_ficha_plano_rascunho_por_paciente'),
        ),
    ]
