# Generated by Django 6.1 on 2026-09-09 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_paciente_redes_e_ficha_plano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAutorizacaoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'rascunho'), ('concluida', 'concluída')], default='rascunho', max_length=20, verbose_name='status')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='nome completo')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('cpf', models.CharField(max_length=18, verbose_name='CPF')),
                ('nome_responsavel', models.CharField(blank=True, max_length=200, verbose_name='responsável legal')),
                ('aceitou_declaracao', models.BooleanField(default=False, verbose_name='aceitou a declaração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacoes_custo', to='core.consulta', verbose_name='consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_autorizacao_custo', to='core.paciente', verbose_name='paciente')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_autorizacao_custo_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
            ],
            options={
                'verbose_name': 'autorização de itens com custo',
                'verbose_name_plural': 'autorizações de itens com custo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemAutorizacaoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('tipo', models.CharField(blank=True, choices=[('receituario_impresso', 'receituário impresso'), ('receituario_digital', 'receituário digital/online'), ('radiografia', 'radiografia (filme ou digital)'), ('fotografias', 'fotografias clínicas'), ('tomografia', 'tomografia'), ('ressonancia', 'ressonância magnética'), ('outros_exames', 'outros exames'), ('materiais', 'materiais utilizados'), ('laboratorio', 'laboratório / prótese'), ('outros', 'outros itens com custo')], max_length=40, verbose_name='tipo')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição / detalhe')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor a cobrar')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.fichaautorizacaocusto', verbose_name='autorização')),
            ],
            options={
                'verbose_name': 'item autorizado com custo',
                'verbose_name_plural': 'itens autorizados com custo',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='fichaautorizacaocusto',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rascunho')), fields=('paciente',), name='uma_autorizacao_custo_rascunho_por_paciente'),
        ),
    ]
