# Generated by Django 6.1 on 2026-09-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ficha_autorizacao_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaautorizacaocusto',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='autorizacoes/%Y/%m/', verbose_name='Arquivo anexado (Raio-X, exame, laudo etc.)'),
        ),
    ]
