# Generated by Django 6.1 on 2026-09-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fichaautorizacaocusto_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('agendada', 'agendada'), ('confirmada', 'confirmada'), ('presente', 'Paciente chegou'), ('realizada', 'realizada'), ('faltou', 'faltou'), ('cancelada', 'cancelada')], default='agendada', max_length=20, verbose_name='status'),
        ),
    ]
