# Generated by Django 6.1 on 2026-09-11 21:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_consulta_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de emissão')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor original')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_receber', to='core.consulta', verbose_name='consulta de origem')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_receber_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_receber', to='core.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'conta a receber',
                'verbose_name_plural': 'contas a receber',
                'ordering': ['data_emissao', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='número da parcela')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor original')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='core.contareceber', verbose_name='conta a receber')),
            ],
            options={
                'verbose_name': 'parcela de conta a receber',
                'verbose_name_plural': 'parcelas de contas a receber',
                'ordering': ['vencimento', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='RecebimentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recebimento', 'recebimento'), ('estorno', 'estorno')], max_length=20, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='desconto aplicado')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'dinheiro'), ('cartao_credito', 'cartão de crédito'), ('pix', 'pix'), ('outros', 'outros')], default='', max_length=20, verbose_name='forma de pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('recebido_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='recebido em')),
                ('numero_recibo', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='número do recibo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_paciente_registrados', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='core.parcelacontareceber', verbose_name='parcela')),
                ('recebimento_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estornos', to='core.recebimentopaciente', verbose_name='recebimento original')),
            ],
            options={
                'verbose_name': 'recebimento de paciente',
                'verbose_name_plural': 'recebimentos de pacientes',
                'ordering': ['recebido_em', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('conta_criada', 'conta criada'), ('recebimento_registrado', 'recebimento registrado'), ('estorno_registrado', 'estorno registrado')], max_length=40, verbose_name='ação')),
                ('descricao', models.CharField(max_length=300, verbose_name='descrição')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='dados da operação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_financeiras', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_financeiras', to='core.contareceber', verbose_name='conta a receber')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_financeiras', to='core.parcelacontareceber', verbose_name='parcela')),
                ('recebimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_financeiras', to='core.recebimentopaciente', verbose_name='recebimento')),
            ],
            options={
                'verbose_name': 'auditoria financeira',
                'verbose_name_plural': 'auditorias financeiras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='contareceber',
            constraint=models.CheckConstraint(condition=models.Q(('valor_original__gt', 0)), name='conta_receber_valor_original_positivo'),
        ),
        migrations.AddConstraint(
            model_name='parcelacontareceber',
            constraint=models.UniqueConstraint(fields=('conta', 'numero'), name='parcela_conta_receber_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='parcelacontareceber',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='parcela_conta_receber_numero_positivo'),
        ),
        migrations.AddConstraint(
            model_name='parcelacontareceber',
            constraint=models.CheckConstraint(condition=models.Q(('valor_original__gt', 0)), name='parcela_conta_receber_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='recebimentopaciente',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='recebimento_paciente_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='recebimentopaciente',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__gte', 0)), name='recebimento_paciente_desconto_nao_negativo'),
        ),
    ]
