# Generated by Django 6.1 on 2026-09-11 21:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contareceber_parcelacontareceber_recebimentopaciente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('cadastrada_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrada em')),
            ],
            options={
                'verbose_name': 'categoria de conta a pagar',
                'verbose_name_plural': 'categorias de contas a pagar',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, unique=True, verbose_name='nome')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('contato', models.CharField(blank=True, max_length=200, verbose_name='contato')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('competencia', models.DateField(verbose_name='competência')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor original')),
                ('recorrencia', models.CharField(choices=[('unica', 'única'), ('mensal', 'mensal'), ('anual', 'anual')], default='unica', max_length=20, verbose_name='recorrência')),
                ('situacao', models.CharField(choices=[('pendente_aprovacao', 'pendente de aprovação'), ('aprovada', 'aprovada'), ('paga', 'paga')], default='pendente_aprovacao', max_length=30, verbose_name='situação')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar', to='core.categoriacontapagar', verbose_name='categoria')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar_criadas', to=settings.AUTH_USER_MODEL, verbose_name='responsável pelo lançamento')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar', to='core.fornecedor', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'conta a pagar',
                'verbose_name_plural': 'contas a pagar',
                'ordering': ['vencimento', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BaixaContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor baixado')),
                ('baixado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='baixado em')),
                ('chave_operacao', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='chave da operação')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas_contas_pagar_registradas', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='core.contapagar', verbose_name='conta a pagar')),
            ],
            options={
                'verbose_name': 'baixa de conta a pagar',
                'verbose_name_plural': 'baixas de contas a pagar',
                'ordering': ['baixado_em', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('conta_criada', 'conta criada'), ('conta_aprovada', 'conta aprovada'), ('baixa_registrada', 'baixa registrada')], max_length=40, verbose_name='ação')),
                ('descricao', models.CharField(max_length=300, verbose_name='descrição')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='dados da operação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_contas_pagar', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('baixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='core.baixacontapagar', verbose_name='baixa')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='core.contapagar', verbose_name='conta a pagar')),
            ],
            options={
                'verbose_name': 'auditoria de conta a pagar',
                'verbose_name_plural': 'auditorias de contas a pagar',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='baixacontapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='baixa_conta_pagar_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor_original__gt', 0)), name='conta_pagar_valor_original_positivo'),
        ),
    ]
