# Generated by Django 6.1 on 2026-09-11 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_contas_pagar_fornecedores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('situacao', models.CharField(choices=[('aberto', 'aberto'), ('fechado', 'fechado')], default='aberto', max_length=10)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('justificativa_diferenca', models.TextField(blank=True)),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('aberto_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL)),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada_automatica', 'entrada automática'), ('saida_automatica', 'saída automática'), ('ajuste_entrada', 'ajuste de entrada'), ('ajuste_saida', 'ajuste de saída'), ('compensacao_entrada', 'compensação de entrada'), ('compensacao_saida', 'compensação de saída')], max_length=25)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('baixa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimento_caixa', to='core.baixacontapagar')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.caixadiario')),
                ('recebido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimento_caixa', to='core.recebimentopaciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='core.caixadiario')),
                ('movimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.movimentocaixa')),
            ],
        ),
        migrations.AddConstraint(
            model_name='movimentocaixa',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='movimento_caixa_valor_positivo'),
        ),
    ]
