# Generated by Django 6.1 on 2026-09-12 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fluxo_caixa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('pendente', 'pendente'), ('conciliada', 'conciliada'), ('parcial', 'parcial'), ('divergente', 'divergente'), ('cancelada', 'cancelada logicamente')], default='pendente', max_length=20, verbose_name='situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_canceladas', to=settings.AUTH_USER_MODEL)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conciliação',
                'verbose_name_plural': 'conciliações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImportacaoExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=120, verbose_name='instituição financeira')),
                ('conta_referencia', models.CharField(max_length=80, verbose_name='conta de referência')),
                ('formato', models.CharField(choices=[('manual', 'manual'), ('csv', 'CSV'), ('ofx', 'OFX')], default='manual', max_length=10, verbose_name='formato de origem')),
                ('hash_arquivo', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='hash do arquivo importado')),
                ('periodo_inicial', models.DateField(blank=True, null=True, verbose_name='período inicial')),
                ('periodo_final', models.DateField(blank=True, null=True, verbose_name='período final')),
                ('situacao', models.CharField(choices=[('importada', 'importada'), ('cancelada', 'cancelada logicamente')], default='importada', max_length=20, verbose_name='situação')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_extrato_canceladas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_extrato_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'importação de extrato',
                'verbose_name_plural': 'importações de extrato',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaConciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=40, verbose_name='ação')),
                ('descricao', models.CharField(max_length=300, verbose_name='descrição')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='dados da operação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('conciliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='core.conciliacao')),
                ('importacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='core.importacaoextrato')),
            ],
            options={
                'verbose_name': 'auditoria de conciliação',
                'verbose_name_plural': 'auditorias de conciliação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_origem', models.PositiveIntegerField(verbose_name='índice na origem')),
                ('referencia_externa', models.CharField(blank=True, max_length=160, verbose_name='referência externa')),
                ('data', models.DateField(verbose_name='data do lançamento')),
                ('descricao', models.CharField(max_length=300, verbose_name='descrição')),
                ('natureza', models.CharField(choices=[('entrada', 'entrada'), ('saida', 'saída')], max_length=10, verbose_name='natureza')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('saldo_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='saldo informado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='core.importacaoextrato')),
            ],
            options={
                'verbose_name': 'lançamento de extrato',
                'verbose_name_plural': 'lançamentos de extrato',
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='conciliacao',
            name='lancamento_extrato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacao', to='core.lancamentoextrato'),
        ),
        migrations.CreateModel(
            name='AjusteConciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('taxa_cartao', 'taxa de cartão'), ('taxa_pix', 'taxa de Pix'), ('outra_taxa', 'outra taxa'), ('divergencia', 'divergência')], max_length=20, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('motivo', models.TextField(verbose_name='motivo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('conciliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='core.conciliacao')),
            ],
            options={
                'verbose_name': 'ajuste de conciliação',
                'verbose_name_plural': 'ajustes de conciliação',
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='ajuste_conciliacao_valor_positivo')],
            },
        ),
        migrations.CreateModel(
            name='ItemConciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_origem', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor da origem')),
                ('valor_conciliado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor conciliado')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('baixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_conciliacao', to='core.baixacontapagar')),
                ('conciliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='core.conciliacao')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('movimento_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_conciliacao', to='core.movimentocaixa')),
                ('recebimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_conciliacao', to='core.recebimentopaciente')),
                ('repasse_uniodonto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_conciliacao', to='core.repasseuniodonto')),
            ],
            options={
                'verbose_name': 'item de conciliação',
                'verbose_name_plural': 'itens de conciliação',
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_origem__gt', 0)), name='item_conciliacao_valor_origem_positivo'), models.CheckConstraint(condition=models.Q(('valor_conciliado__gt', 0)), name='item_conciliacao_valor_conciliado_positivo')],
            },
        ),
        migrations.AddConstraint(
            model_name='lancamentoextrato',
            constraint=models.UniqueConstraint(fields=('importacao', 'indice_origem'), name='lancamento_extrato_indice_unico_por_importacao'),
        ),
        migrations.AddConstraint(
            model_name='lancamentoextrato',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='lancamento_extrato_valor_positivo'),
        ),
    ]
