# Generated by Django 6.1 on 2026-09-12 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_conciliacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='auditoriaconciliacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conciliacao__isnull', False), ('importacao__isnull', True)), models.Q(('conciliacao__isnull', True), ('importacao__isnull', False)), _connector='OR'), name='auditoria_conciliacao_um_alvo'),
        ),
        migrations.AddConstraint(
            model_name='itemconciliacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recebimento__isnull', False), ('baixa__isnull', True), ('movimento_caixa__isnull', True), ('repasse_uniodonto__isnull', True)), models.Q(('recebimento__isnull', True), ('baixa__isnull', False), ('movimento_caixa__isnull', True), ('repasse_uniodonto__isnull', True)), models.Q(('recebimento__isnull', True), ('baixa__isnull', True), ('movimento_caixa__isnull', False), ('repasse_uniodonto__isnull', True)), models.Q(('recebimento__isnull', True), ('baixa__isnull', True), ('movimento_caixa__isnull', True), ('repasse_uniodonto__isnull', False)), _connector='OR'), name='item_conciliacao_uma_origem'),
        ),
    ]
