# Generated by Django 6.1 on 2026-09-12 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_formas_iniciais(apps, schema_editor):
    FormaPagamento = apps.get_model('core', 'FormaPagamentoConfiguravel')
    for codigo, nome in (
        ('pix', 'Pix'),
        ('dinheiro', 'Dinheiro'),
        ('cartao_debito', 'Cartão de Débito'),
        ('cartao_credito', 'Cartão de Crédito'),
        ('transferencia', 'Transferência'),
    ):
        FormaPagamento.objects.get_or_create(
            codigo=codigo,
            defaults={'nome': nome, 'ativo': True},
        )


def remover_formas_iniciais(apps, schema_editor):
    FormaPagamento = apps.get_model('core', 'FormaPagamentoConfiguravel')
    FormaPagamento.objects.filter(
        codigo__in=['pix', 'dinheiro', 'cartao_debito', 'cartao_credito', 'transferencia'],
        recebimentos__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_integridade_conciliacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamentoConfiguravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('codigo', models.SlugField(max_length=30, unique=True, verbose_name='código')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo_taxa', models.CharField(choices=[('nenhuma', 'sem taxa'), ('percentual', 'percentual'), ('valor_fixo', 'valor fixo')], default='nenhuma', max_length=15, verbose_name='tipo de taxa')),
                ('valor_taxa', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='valor da taxa')),
                ('prazo_recebimento_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='prazo de recebimento (dias)')),
                ('conta_destino', models.CharField(blank=True, max_length=160, verbose_name='conta/destino')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'forma de pagamento configurável',
                'verbose_name_plural': 'formas de pagamento configuráveis',
                'ordering': ['nome'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_taxa__gte', 0)), name='forma_pagamento_taxa_nao_negativa')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaFormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=40, verbose_name='ação')),
                ('descricao', models.CharField(max_length=300, verbose_name='descrição')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='dados da operação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='core.formapagamentoconfiguravel')),
            ],
            options={
                'verbose_name': 'auditoria de forma de pagamento',
                'verbose_name_plural': 'auditorias de formas de pagamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='recebimentopaciente',
            name='forma_pagamento_configurada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='core.formapagamentoconfiguravel', verbose_name='forma de pagamento configurada'),
        ),
        migrations.RunPython(criar_formas_iniciais, remover_formas_iniciais),
    ]
