# Generated by Django 6.1 on 2026-09-14 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_formas_pagamento_configuraveis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturaeletronica',
            name='tipo_documento',
            field=models.CharField(choices=[('componente_teste', 'componente de teste'), ('retificacao', 'retificação de documento'), ('evolucao', 'evolução'), ('plano_tratamento', 'plano de tratamento / consentimento'), ('plano_procedimento', 'consentimento por procedimento'), ('plano_profissional', 'assinatura profissional do plano'), ('anamnese', 'cadastro / anamnese'), ('autorizacao_custo', 'autorização de itens com custo')], max_length=40, verbose_name='tipo do documento'),
        ),
        migrations.CreateModel(
            name='RetificacaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_profissional', models.CharField(max_length=200, verbose_name='profissional')),
                ('cro', models.CharField(max_length=30, verbose_name='CRO')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrada em')),
                ('justificativa', models.TextField(verbose_name='justificativa')),
                ('conteudo', models.TextField(verbose_name='conteúdo da retificação')),
                ('anamnese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retificacoes', to='core.fichacadastroanamnese')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retificacoes_documentos', to=settings.AUTH_USER_MODEL)),
                ('autorizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retificacoes', to='core.fichaautorizacaocusto')),
                ('evolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retificacoes', to='core.registroevolucaoclinica')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retificacoes', to='core.fichaplanotratamento')),
            ],
            options={
                'verbose_name': 'retificação de documento',
                'verbose_name_plural': 'retificações de documentos',
                'ordering': ['criado_em', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('anamnese__isnull', True), ('autorizacao__isnull', True), ('evolucao__isnull', False), ('plano__isnull', True)), models.Q(('anamnese__isnull', False), ('autorizacao__isnull', True), ('evolucao__isnull', True), ('plano__isnull', True)), models.Q(('anamnese__isnull', True), ('autorizacao__isnull', True), ('evolucao__isnull', True), ('plano__isnull', False)), models.Q(('anamnese__isnull', True), ('autorizacao__isnull', False), ('evolucao__isnull', True), ('plano__isnull', True)), _connector='OR'), name='retificacao_exatamente_um_original')],
            },
        ),
    ]
