# Generated by Django 6.1 on 2026-09-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_retificacao_documento'),
        ('locacao', '0009_despesa_conta_pagar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPrescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('medicamento', models.CharField(blank=True, max_length=200, verbose_name='medicamento')),
                ('concentracao_apresentacao', models.CharField(blank=True, max_length=200, verbose_name='concentração / apresentação')),
                ('quantidade', models.CharField(blank=True, max_length=100, verbose_name='quantidade')),
                ('posologia', models.TextField(blank=True, verbose_name='posologia')),
                ('via', models.CharField(blank=True, max_length=100, verbose_name='via')),
                ('duracao', models.CharField(blank=True, max_length=100, verbose_name='duração')),
                ('orientacoes', models.TextField(blank=True, verbose_name='orientações do medicamento')),
            ],
            options={
                'verbose_name': 'medicamento da prescrição',
                'verbose_name_plural': 'medicamentos da prescrição',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=200, verbose_name='nome do paciente')),
                ('cpf_paciente', models.CharField(blank=True, max_length=18, verbose_name='CPF do paciente')),
                ('data_nascimento_paciente', models.DateField(blank=True, null=True, verbose_name='nascimento do paciente')),
                ('nome_profissional', models.CharField(max_length=200, verbose_name='profissional responsável')),
                ('cro', models.CharField(blank=True, max_length=30, verbose_name='CRO / UF')),
                ('texto_livre', models.TextField(blank=True, verbose_name='texto livre da prescrição')),
                ('orientacoes', models.TextField(blank=True, verbose_name='orientações gerais')),
                ('status', models.CharField(choices=[('rascunho', 'rascunho'), ('assinada', 'assinada')], default='rascunho', max_length=20, verbose_name='situação')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='versão do rascunho')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('emitida_em', models.DateTimeField(blank=True, null=True, verbose_name='emitida em')),
            ],
            options={
                'verbose_name': 'prescrição',
                'verbose_name_plural': 'prescrições',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='retificacaodocumento',
            name='retificacao_exatamente_um_original',
        ),
        migrations.AlterField(
            model_name='assinaturaeletronica',
            name='tipo_documento',
            field=models.CharField(choices=[('componente_teste', 'componente de teste'), ('retificacao', 'retificação de documento'), ('prescricao', 'prescrição'), ('evolucao', 'evolução'), ('plano_tratamento', 'plano de tratamento / consentimento'), ('plano_procedimento', 'consentimento por procedimento'), ('plano_profissional', 'assinatura profissional do plano'), ('anamnese', 'cadastro / anamnese'), ('autorizacao_custo', 'autorização de itens com custo')], max_length=40, verbose_name='tipo do documento'),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='locacao.dentista'),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='itemprescricao',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.prescricao', verbose_name='prescrição'),
        ),
        migrations.AddField(
            model_name='retificacaodocumento',
            name='prescricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retificacoes', to='core.prescricao'),
        ),
        migrations.AddConstraint(
            model_name='retificacaodocumento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(models.Q(('anamnese__isnull', True), ('autorizacao__isnull', True), ('evolucao__isnull', False), ('plano__isnull', True)), models.Q(('anamnese__isnull', False), ('autorizacao__isnull', True), ('evolucao__isnull', True), ('plano__isnull', True)), models.Q(('anamnese__isnull', True), ('autorizacao__isnull', True), ('evolucao__isnull', True), ('plano__isnull', False)), models.Q(('anamnese__isnull', True), ('autorizacao__isnull', False), ('evolucao__isnull', True), ('plano__isnull', True)), _connector='OR'), ('prescricao__isnull', True)), models.Q(('anamnese__isnull', True), ('autorizacao__isnull', True), ('evolucao__isnull', True), ('plano__isnull', True), ('prescricao__isnull', False)), _connector='OR'), name='retificacao_exatamente_um_original'),
        ),
    ]
