# Generated by Django 6.1 on 2026-09-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_prescricoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
