# Generated by Django 6.1 on 2026-09-14 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_paciente_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalizacaoFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='fichas_legado/%Y/%m/', verbose_name='imagem')),
                ('tipo', models.CharField(choices=[('anamnese', 'Anamnese'), ('evolucao', 'Evolução'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='tipo')),
                ('texto_bruto_ia', models.JSONField(blank=True, default=dict, verbose_name='texto bruto da IA')),
                ('status', models.CharField(choices=[('pendente_revisao', 'Pendente de revisão'), ('confirmada', 'Confirmada')], default='pendente_revisao', max_length=30, verbose_name='status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('digitalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_digitalizadas', to=settings.AUTH_USER_MODEL, verbose_name='digitalizado por')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digitalizacoes', to='core.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'digitalização de ficha',
                'verbose_name_plural': 'digitalizações de ficha',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='registroevolucaoclinica',
            name='origem',
            field=models.CharField(choices=[('nativo', 'Nativo'), ('legado_ficha_fisica', 'Legado - ficha física')], default='nativo', max_length=30, verbose_name='origem'),
        ),
        migrations.AddField(
            model_name='registroevolucaoclinica',
            name='digitalizado_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolucoes_geradas', to='core.digitalizacaoficha', verbose_name='digitalizado de'),
        ),
    ]
