# Generated by Django 6.1 on 2026-09-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_digitalizacaoficha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalizacaoficha',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('cadastro', 'Cadastro'),
                    ('anamnese', 'Anamnese'),
                    ('evolucao', 'Evolução'),
                    ('outro', 'Outro'),
                ],
                default='outro',
                max_length=20,
                verbose_name='tipo',
            ),
        ),
    ]
