# Generated by Django 6.1 on 2026-09-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_digitalizacaoficha_tipo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='precoprocedimento',
            name='preco_unico_procedimento_tabela',
        ),
        migrations.AddConstraint(
            model_name='precoprocedimento',
            constraint=models.UniqueConstraint(condition=models.Q(('convenio__isnull', False)), fields=('procedimento', 'convenio'), name='preco_unico_procedimento_convenio'),
        ),
        migrations.AddConstraint(
            model_name='precoprocedimento',
            constraint=models.UniqueConstraint(condition=models.Q(('convenio__isnull', True)), fields=('procedimento',), name='preco_unico_procedimento_particular'),
        ),
    ]
