# Generated by Django 6.1 on 2026-09-29 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_preco_procedimento_unicidade_parcial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criado', 'criado'), ('alterado', 'alterado'), ('desativado', 'desativado'), ('reativado', 'reativado')], max_length=20, verbose_name='ação')),
                ('origem', models.CharField(choices=[('tela', 'tela do sistema'), ('administracao', 'administração')], max_length=20, verbose_name='origem')),
                ('alteracoes', models.JSONField(blank=True, default=dict, verbose_name='alterações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='core.paciente', verbose_name='paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_paciente', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'auditoria de paciente',
                'verbose_name_plural': 'auditorias de paciente',
                'ordering': ['-criado_em'],
            },
        ),
    ]
