# Generated by Django 6.1 on 2026-09-29 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auditoria_paciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_digitado', models.CharField(blank=True, default='', max_length=150, verbose_name='usuário digitado')),
                ('tipo', models.CharField(choices=[('entrou', 'entrou'), ('saiu', 'saiu'), ('tentativa_falhou', 'tentativa falhou')], max_length=20, verbose_name='tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_acesso', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'registro de acesso',
                'verbose_name_plural': 'registros de acesso',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='dia')),
                ('primeira_atividade', models.DateTimeField(verbose_name='primeira atividade')),
                ('ultima_atividade', models.DateTimeField(verbose_name='última atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades_diarias', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'atividade diária',
                'verbose_name_plural': 'atividades diárias',
                'ordering': ['-data', 'usuario_id'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'data'), name='atividade_diaria_unica')],
            },
        ),
    ]
