# Generated by Django 6.1 on 2026-09-30 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_registro_acesso_atividade_diaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalizacaoficha',
            name='motivo_refazer',
            field=models.TextField(blank=True, default='', verbose_name='motivo para refazer'),
        ),
        migrations.AddField(
            model_name='digitalizacaoficha',
            name='revisado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='revisado em'),
        ),
        migrations.AddField(
            model_name='digitalizacaoficha',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='revisado por'),
        ),
        migrations.AddField(
            model_name='digitalizacaoficha',
            name='motivo_engano',
            field=models.TextField(blank=True, default='', verbose_name='motivo do engano'),
        ),
        migrations.AlterField(
            model_name='digitalizacaoficha',
            name='status',
            field=models.CharField(choices=[('pendente_revisao', 'Pendente'), ('confirmada', 'Conferida'), ('refazer', 'Refazer foto'), ('engano', 'Enviada por engano')], default='pendente_revisao', max_length=30, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='TrocaPacienteDigitalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='motivo')),
                ('trocado_em', models.DateTimeField(auto_now_add=True, verbose_name='trocado em')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_paciente', to='core.digitalizacaoficha', verbose_name='ficha')),
                ('paciente_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paciente', verbose_name='paciente anterior')),
                ('paciente_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paciente', verbose_name='paciente novo')),
                ('trocado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_digitalizacao', to=settings.AUTH_USER_MODEL, verbose_name='trocado por')),
            ],
            options={
                'verbose_name': 'troca de paciente da digitalização',
                'verbose_name_plural': 'trocas de paciente da digitalização',
                'ordering': ['-trocado_em'],
            },
        ),
        migrations.AddField(
            model_name='registroacesso',
            name='digitalizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos', to='core.digitalizacaoficha', verbose_name='ficha digitalizada'),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='tipo',
            field=models.CharField(choices=[('entrou', 'entrou'), ('saiu', 'saiu'), ('tentativa_falhou', 'tentativa falhou'), ('abriu_foto', 'abriu foto da ficha')], max_length=20, verbose_name='tipo'),
        ),
    ]
