# Generated by Django 6.1 on 2026-09-30 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_registro_acesso_atividade_diaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalizacaoficha',
            name='motivo_refazer',
            field=models.TextField(blank=True, default='', verbose_name='motivo para refazer'),
        ),
        migrations.AddField(
            model_name='digitalizacaoficha',
            name='revisado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='revisado em'),
        ),
        migrations.AddField(
            model_name='digitalizacaoficha',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='revisado por'),
        ),
        migrations.AlterField(
            model_name='digitalizacaoficha',
            name='status',
            field=models.CharField(choices=[('pendente_revisao', 'Pendente'), ('confirmada', 'Conferida'), ('refazer', 'Refazer foto')], default='pendente_revisao', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='tipo',
            field=models.CharField(choices=[('entrou', 'entrou'), ('saiu', 'saiu'), ('tentativa_falhou', 'tentativa falhou'), ('abriu_foto', 'abriu foto da ficha')], max_length=20, verbose_name='tipo'),
        ),
    ]
