# Generated by Django 6.1 on 2026-10-05 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_revisao_fichas_digitalizadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='aceita_lembretes_whatsapp',
            field=models.BooleanField(default=False, help_text='Só recebe lembrete quem autorizou. O texto leva data, hora e dentista, sem conteúdo clínico.', verbose_name='aceita lembretes por WhatsApp'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='aceita_lembretes_whatsapp_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='autorizou lembretes em'),
        ),
        migrations.AlterField(
            model_name='auditoriaconsulta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_consulta', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.CreateModel(
            name='MensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('direcao', models.CharField(choices=[('enviada', 'enviada'), ('recebida', 'recebida')], max_length=20, verbose_name='direção')),
                ('texto', models.TextField(verbose_name='texto')),
                ('status', models.CharField(choices=[('simulada', 'simulada'), ('enviada', 'enviada'), ('falhou', 'falhou'), ('recebida', 'recebida')], max_length=20, verbose_name='status')),
                ('id_externo', models.CharField(blank=True, default='', max_length=255, verbose_name='id externo')),
                ('acao', models.CharField(blank=True, choices=[('confirmou', 'confirmou'), ('desmarcou', 'desmarcou'), ('precisa_atencao', 'precisa de atenção')], default='', max_length=20, verbose_name='ação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_whatsapp', to='core.consulta', verbose_name='consulta')),
                ('lembrete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='core.mensagemwhatsapp', verbose_name='lembrete')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_whatsapp', to='core.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'mensagem de WhatsApp',
                'verbose_name_plural': 'mensagens de WhatsApp',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['telefone', 'direcao', 'criado_em'], name='whatsapp_telefone_direcao')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('direcao', 'enviada')), fields=('consulta',), name='lembrete_whatsapp_unico_por_consulta'), models.UniqueConstraint(condition=models.Q(('id_externo', ''), _negated=True), fields=('id_externo',), name='mensagem_whatsapp_id_externo_unico')],
            },
        ),
    ]
