# Generated by Django 6.1 on 2026-10-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_lembrete_whatsapp_simulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalizacaoficha',
            name='lote',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='lote de envio'),
        ),
        migrations.AddField(
            model_name='digitalizacaoficha',
            name='ordem',
            field=models.PositiveIntegerField(default=1, verbose_name='ordem da folha'),
        ),
    ]
