# Generated by Django 6.1 on 2026-10-05 12:55

from django.db import migrations, models


def preencher_busca(apps, schema_editor):
    from core.busca_paciente import normalizar_nome, somente_digitos

    Paciente = apps.get_model('core', 'Paciente')
    for paciente in Paciente.objects.all().iterator():
        Paciente.objects.filter(pk=paciente.pk).update(
            nome_busca=normalizar_nome(paciente.nome_completo),
            cpf_busca=somente_digitos(paciente.cpf),
            telefone_busca=somente_digitos(paciente.telefone),
            whatsapp_busca=somente_digitos(paciente.whatsapp),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_ordem_lote_digitalizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf_busca',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='CPF para busca'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_busca',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='nome para busca'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone_busca',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='telefone para busca'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='whatsapp_busca',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='WhatsApp para busca'),
        ),
        migrations.RunPython(preencher_busca, migrations.RunPython.noop),
    ]
