# Generated by Django 6.1 on 2026-10-05

from django.db import migrations


def arrumar_nomes(apps, schema_editor):
    from core.busca_paciente import formatar_nome, normalizar_nome

    Paciente = apps.get_model('core', 'Paciente')
    for paciente in Paciente.objects.all().iterator():
        nome = formatar_nome(paciente.nome_completo)
        Paciente.objects.filter(pk=paciente.pk).update(
            nome_completo=nome,
            nome_busca=normalizar_nome(nome),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_busca_paciente'),
    ]

    operations = [
        migrations.RunPython(arrumar_nomes, migrations.RunPython.noop),
    ]
