# Generated by Django 6.1 on 2026-10-05 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_reaplicar_nome_homolog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalizacaoficha',
            name='tipo',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('anamnese', 'Anamnese'), ('evolucao', 'Evolução'), ('encaminhamento', 'Encaminhamento / carta de indicação'), ('convenio', 'Guia / ficha do convênio'), ('exame', 'Exame / raio-X em papel'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='TrocaTipoDigitalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anterior', models.CharField(max_length=20, verbose_name='tipo anterior')),
                ('tipo_novo', models.CharField(max_length=20, verbose_name='tipo novo')),
                ('trocado_em', models.DateTimeField(auto_now_add=True, verbose_name='trocado em')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_tipo', to='core.digitalizacaoficha', verbose_name='ficha')),
                ('trocado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_tipo_digitalizacao', to=settings.AUTH_USER_MODEL, verbose_name='trocado por')),
            ],
            options={
                'verbose_name': 'troca de tipo da digitalização',
                'verbose_name_plural': 'trocas de tipo da digitalização',
                'ordering': ['-trocado_em'],
            },
        ),
    ]
