# Generated by Django 6.1 on 2026-10-09 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_ordem_folhas_continua"),
        ("locacao", "0012_perfilusuario_modo_simples"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fichacadastroanamnese",
            name="uma_ficha_anamnese_aberta_por_paciente",
        ),
        migrations.AddField(
            model_name="fichacadastroanamnese",
            name="hof_intercorrencias",
            field=models.TextField(
                blank=True,
                verbose_name="intercorrências, nódulos, infecções ou reações anteriores",
            ),
        ),
        migrations.AddField(
            model_name="fichacadastroanamnese",
            name="hof_procedimentos",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="procedimentos estéticos anteriores",
            ),
        ),
        migrations.AddField(
            model_name="fichacadastroanamnese",
            name="hof_situacoes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="situações relevantes"
            ),
        ),
        migrations.AddField(
            model_name="fichacadastroanamnese",
            name="hof_situacoes_detalhes",
            field=models.TextField(
                blank=True, verbose_name="detalhes das situações relevantes"
            ),
        ),
        migrations.AddField(
            model_name="fichacadastroanamnese",
            name="hof_ultimo_procedimento",
            field=models.TextField(
                blank=True,
                verbose_name="produto / região / data do último procedimento",
            ),
        ),
        migrations.AddField(
            model_name="fichacadastroanamnese",
            name="isotretinoina",
            field=models.CharField(
                blank=True,
                choices=[("sim", "sim"), ("nao", "não")],
                default="",
                max_length=20,
                verbose_name="usa ou usou isotretinoína (Roacutan)",
            ),
        ),
        migrations.AddField(
            model_name="fichacadastroanamnese",
            name="isotretinoina_quando",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="quando usou a isotretinoína"
            ),
        ),
        migrations.AddField(
            model_name="fichacadastroanamnese",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("odontologica", "odontológica"),
                    ("hof", "harmonização orofacial (HOF)"),
                ],
                default="odontologica",
                max_length=20,
                verbose_name="tipo de anamnese",
            ),
        ),
        migrations.AddConstraint(
            model_name="fichacadastroanamnese",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["rascunho", "aguardando_dentista"])),
                fields=("paciente", "tipo"),
                name="uma_ficha_anamnese_aberta_por_paciente_e_tipo",
            ),
        ),
    ]
