"""
Django settings for consultorio project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _carregar_dotenv(caminho):
    """Preenche os.environ com chaves ausentes a partir de um .env local.

    Não sobrescreve variáveis já definidas (ex.: painel do Render).
    """
    if not caminho.is_file():
        return
    for linha in caminho.read_text(encoding='utf-8').splitlines():
        linha = linha.strip()
        if not linha or linha.startswith('#') or '=' not in linha:
            continue
        chave, _, valor = linha.partition('=')
        chave = chave.strip()
        valor = valor.strip().strip('"').strip("'")
        if chave:
            os.environ.setdefault(chave, valor)


_carregar_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Produção (Render): definir SECRET_KEY no painel do serviço (Environment).
# Local: copiar .env.example para .env e gerar uma chave (não versionar o .env).
SECRET_KEY = os.environ.get('SECRET_KEY', '').strip()
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'SECRET_KEY não está configurada. Defina a variável de ambiente '
        'SECRET_KEY (no Render: Environment do serviço; no desenvolvimento: '
        'arquivo .env na raiz do projeto, fora do Git).'
    )

# O Render sempre roda em produção; uma variável DEBUG acidental não pode
# reativar páginas de erro detalhadas nesse ambiente.
EM_PRODUCAO = bool(os.environ.get('RENDER')) or os.environ.get(
    'DJANGO_ENV', ''
).lower() == 'production'
if EM_PRODUCAO and (
    len(SECRET_KEY) < 50 or SECRET_KEY.startswith('django-insecure-')
):
    raise ImproperlyConfigured(
        'SECRET_KEY de produção deve ser aleatória, exclusiva e ter ao menos '
        '50 caracteres. Configure-a somente no ambiente seguro do Render.'
    )
DEBUG = not EM_PRODUCAO and os.environ.get('DEBUG', 'True').lower() in (
    'true', '1', 'yes'
)

def _lista_de_ambiente(nome):
    return [item.strip() for item in os.environ.get(nome, '').split(',') if item.strip()]


def _inteiro_positivo_de_ambiente(nome, padrao):
    try:
        valor = int(os.environ.get(nome, str(padrao)))
    except ValueError as exc:
        raise ImproperlyConfigured(f'{nome} precisa ser um inteiro positivo.') from exc
    if valor < 1:
        raise ImproperlyConfigured(f'{nome} precisa ser maior que zero.')
    return valor


def _flag_ambiente(environ, nome):
    return str(environ.get(nome, '') or '').strip().lower() in ('true', '1', 'yes')


def _pastas_homolog_local(base_dir):
    raiz = Path(base_dir) / 'homolog_local'
    return {
        'media': (raiz / 'media').resolve(),
        'exames': (raiz / 'private_exames').resolve(),
        'tmp': (raiz / 'tmp').resolve(),
    }


def _caminho_no_projeto(base_dir, valor):
    caminho = Path(valor)
    if not caminho.is_absolute():
        caminho = Path(base_dir) / caminho
    return caminho


def _resolver_exames_root_ambiente(environ, base_dir):
    configurada = str(environ.get('EXAMES_ROOT', '') or '').strip()
    if configurada:
        return _caminho_no_projeto(base_dir, configurada)
    return Path(base_dir) / 'private_exames'


def resolver_media_root(em_producao, environ, base_dir):
    """MEDIA_ROOT: disco do Render em produção; opcional DJANGO_MEDIA_ROOT só no local."""
    if em_producao:
        raiz_midia = str(environ.get('RENDER_DISK_PATH', '') or '').strip()
        if not raiz_midia:
            raise ImproperlyConfigured(
                'RENDER_DISK_PATH é obrigatório para armazenar mídia em disco persistente.'
            )
        return Path(raiz_midia) / 'media'
    configurada = str(environ.get('DJANGO_MEDIA_ROOT', '') or '').strip()
    if configurada:
        return _caminho_no_projeto(base_dir, configurada)
    return Path(base_dir) / 'media'


def resolver_upload_temp_local(em_producao, environ, base_dir):
    """FILE_UPLOAD_TEMP_DIR opcional só fora de produção; produção mantém o padrão do Django."""
    if em_producao:
        return None
    configurada = str(environ.get('DJANGO_FILE_UPLOAD_TEMP_DIR', '') or '').strip()
    if not configurada:
        return None
    return str(_caminho_no_projeto(base_dir, configurada))


def validar_homolog_local(
    environ,
    *,
    em_producao,
    media_root,
    file_upload_temp_dir,
    database_name,
    database_engine,
    base_dir,
):
    """Aborta o processo se HOMOLOG_LOCAL=1 e o isolamento não estiver completo."""
    if not _flag_ambiente(environ, 'HOMOLOG_LOCAL'):
        return
    if em_producao:
        raise ImproperlyConfigured(
            'HOMOLOG_LOCAL não pode estar ativo em produção.'
        )
    engine = str(database_engine or '').lower().replace('-', '_')
    if 'postgres' not in engine:
        raise ImproperlyConfigured(
            'HOMOLOG_LOCAL exige PostgreSQL no banco consultorio_homolog.'
        )
    nome = Path(str(database_name or '')).name
    if nome != 'consultorio_homolog':
        raise ImproperlyConfigured(
            'HOMOLOG_LOCAL exige o banco PostgreSQL consultorio_homolog.'
        )
    pastas = _pastas_homolog_local(base_dir)
    if Path(media_root).resolve() != pastas['media']:
        raise ImproperlyConfigured(
            'HOMOLOG_LOCAL exige MEDIA_ROOT em homolog_local/media.'
        )
    exames_root = _resolver_exames_root_ambiente(environ, base_dir)
    if exames_root.resolve() != pastas['exames']:
        raise ImproperlyConfigured(
            'HOMOLOG_LOCAL exige EXAMES_ROOT em homolog_local/private_exames.'
        )
    if not file_upload_temp_dir or Path(file_upload_temp_dir).resolve() != pastas['tmp']:
        raise ImproperlyConfigured(
            'HOMOLOG_LOCAL exige FILE_UPLOAD_TEMP_DIR em homolog_local/tmp.'
        )
    for pasta in pastas.values():
        pasta.mkdir(parents=True, exist_ok=True)


_hosts_configurados = _lista_de_ambiente('DJANGO_ALLOWED_HOSTS')
_host_render = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
ALLOWED_HOSTS = list(dict.fromkeys([
    'consultorio-a7um.onrender.com',
    '127.0.0.1',
    'localhost',
    '192.168.1.103',
    *_hosts_configurados,
    *([_host_render] if _host_render else []),
]))
if EM_PRODUCAO and not _host_render and not _hosts_configurados:
    raise ImproperlyConfigured(
        'Defina RENDER_EXTERNAL_HOSTNAME ou DJANGO_ALLOWED_HOSTS em produção.'
    )

# Render termina TLS no proxy e encaminha X-Forwarded-Proto para a aplicação.
# Estas opções só são forçadas em produção para manter o runserver local simples.
_origens_configuradas = _lista_de_ambiente('CSRF_TRUSTED_ORIGINS')
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys([
    'https://consultorio-a7um.onrender.com',
    *[f'https://{host}' for host in _hosts_configurados if host not in {'localhost', '127.0.0.1'}],
    *([f'https://{_host_render}'] if _host_render else []),
    *_origens_configuradas,
]))
if EM_PRODUCAO:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31_536_000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS', 'false'
    ).lower() in ('true', '1', 'yes')
    SECURE_HSTS_PRELOAD = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'exames.apps.ExamesConfig',
    'locacao.apps.LocacaoConfig',
    'ia_seguranca',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'consultorio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.admin_local_date',
                'core.context_processors.permissoes_usuario',
                'core.context_processors.navegacao_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'consultorio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

banco_url = os.environ.get('DATABASE_URL', '').strip()
if EM_PRODUCAO and not banco_url:
    raise ImproperlyConfigured(
        'DATABASE_URL é obrigatória em produção. Use o PostgreSQL do Render.'
    )
if banco_url:
    try:
        import dj_database_url
    except ImportError as exc:
        raise ImproperlyConfigured(
            'dj-database-url não está instalado para configurar PostgreSQL.'
        ) from exc
    DATABASES = {
        'default': dj_database_url.parse(
            banco_url,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=EM_PRODUCAO,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

LOGIN_URL = 'entrar'
LOGIN_REDIRECT_URL = 'core:inicio'
LOGOUT_REDIRECT_URL = 'entrar'

# Limites de disponibilidade para o processamento síncrono de áudio. Podem ser
# reduzidos via Environment sem aceitar valores inválidos em produção.
IA_AUDIO_MAX_BYTES = _inteiro_positivo_de_ambiente(
    'IA_AUDIO_MAX_BYTES', 10 * 1024 * 1024
)
IA_AUDIO_MAX_DURATION_SECONDS = _inteiro_positivo_de_ambiente(
    'IA_AUDIO_MAX_DURATION_SECONDS', 15 * 60
)
IA_FFMPEG_TIMEOUT_SECONDS = _inteiro_positivo_de_ambiente(
    'IA_FFMPEG_TIMEOUT_SECONDS', 120
)
IA_AUDIO_CONTENT_TYPES = (
    'audio/webm',
    'audio/ogg',
    'audio/wav',
    'audio/x-wav',
    'audio/mpeg',
    'audio/mp4',
    'audio/x-m4a',
)
FILE_UPLOAD_HANDLERS = [
    'ia_seguranca.uploads.LimiteAudioTranscricaoUploadHandler',
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = resolver_media_root(EM_PRODUCAO, os.environ, BASE_DIR)
_upload_temp_local = resolver_upload_temp_local(EM_PRODUCAO, os.environ, BASE_DIR)
if _upload_temp_local:
    FILE_UPLOAD_TEMP_DIR = _upload_temp_local
validar_homolog_local(
    os.environ,
    em_producao=EM_PRODUCAO,
    media_root=MEDIA_ROOT,
    file_upload_temp_dir=globals().get('FILE_UPLOAD_TEMP_DIR'),
    database_name=DATABASES['default'].get('NAME'),
    database_engine=DATABASES['default'].get('ENGINE'),
    base_dir=BASE_DIR,
)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

if EM_PRODUCAO:
    _smtp_obrigatorio = ('SMTP_HOST', 'SMTP_USERNAME', 'SMTP_PASSWORD', 'DEFAULT_FROM_EMAIL')
    _smtp_ausente = [nome for nome in _smtp_obrigatorio if not os.environ.get(nome)]
    if _smtp_ausente:
        raise ImproperlyConfigured(
            'Configuração SMTP ausente em produção: ' + ', '.join(_smtp_ausente)
        )
    _smtp_ssl = os.environ.get('SMTP_USE_SSL', 'false').lower() in ('true', '1', 'yes')
    _smtp_tls = os.environ.get('SMTP_USE_TLS', 'true').lower() in ('true', '1', 'yes')
    if _smtp_ssl and _smtp_tls:
        raise ImproperlyConfigured('SMTP_USE_SSL e SMTP_USE_TLS não podem ser usados juntos.')
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': os.environ['SMTP_HOST'],
                'port': int(os.environ.get('SMTP_PORT', '465' if _smtp_ssl else '587')),
                'username': os.environ['SMTP_USERNAME'],
                'password': os.environ['SMTP_PASSWORD'],
                'use_tls': _smtp_tls,
                'use_ssl': _smtp_ssl,
                'timeout': 10,
            },
        },
    }
    DEFAULT_FROM_EMAIL = os.environ['DEFAULT_FROM_EMAIL']
else:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        },
    }
