from django.urls import path
from .alerta_horario import listar_entradas_fora_do_horario
from .views import (
    inicio,
    administracao,
    ficha_paciente,
    listar_pacientes,
    buscar_pacientes,
    cadastrar_paciente,
    editar_paciente,
    digitalizacao_upload,
    digitalizacao_processar_ia,
    listar_convenios,
    cadastrar_convenio,
    editar_convenio,
    listar_tabela_uniodonto,
    listar_repasses_uniodonto,
    cadastrar_repasse_uniodonto,
    editar_repasse_uniodonto,
    sugestao_producao_uniodonto,
    listar_consultas,
    marcar_consulta_paga,
    agendar_consulta,
    horarios_ocupados,
    remarcar_consulta,
    ficha_consulta,
    alterar_status_consulta,
    lancar_atendimento,
    complementar_dentista,
    listar_procedimentos,
    cadastrar_procedimento,
    editar_procedimento,
    listar_pagamentos_consulta,
    salvar_forma_pagamento,
    listar_contas_receber,
    listar_inadimplencia,
    relatorios_financeiros,
    listar_fornecedores,
    cadastrar_fornecedor,
    listar_categorias_conta_pagar,
    cadastrar_categoria_conta_pagar,
    listar_contas_pagar,
    criar_conta_pagar,
    detalhe_conta_pagar,
    aprovar_conta_pagar,
    registrar_baixa_conta_pagar,
    caixa_diario,
    abrir_caixa,
    movimento_manual_caixa,
    fechar_caixa,
    listar_conciliacoes,
    criar_importacao_extrato_manual,
    detalhe_importacao_extrato,
    criar_lancamento_extrato_manual,
    conciliar_lancamento_extrato,
    registrar_ajuste_conciliacao,
    cancelar_conciliacao,
    listar_formas_pagamento_configuraveis,
    cadastrar_forma_pagamento_configuravel,
    editar_forma_pagamento_configuravel,
    criar_conta_receber,
    detalhe_conta_receber,
    registrar_recebimento,
    estornar_recebimento,
    ver_recibo_recebimento,
    listar_materiais_dia,
    materiais_consulta,
    editar_material_usado,
    excluir_material_usado,
    teste_assinatura,
    ver_imagem_assinatura,
    listar_fichas_anamnese,
    nova_ficha_anamnese,
    renovar_link_anamnese,
    editar_ficha_anamnese,
    ver_ficha_anamnese,
    ficha_anamnese_publica,
    ficha_anamnese_enviada,
    ficha_evolucao_clinica,
    listar_fichas_plano,
    nova_ficha_plano,
    editar_ficha_plano,
    ver_ficha_plano,
    listar_fichas_autorizacao,
    nova_ficha_autorizacao,
    nova_ficha_autorizacao_consulta,
    editar_ficha_autorizacao,
    ver_ficha_autorizacao,
)

app_name = 'core'
from django.urls import include

from .digitalizacao_revisao import (
    conferir_folhas_paciente,
    conferir_folhas_sem_paciente,
    detalhe_digitalizacao,
    folhas_paciente,
    folhas_sem_paciente,
    foto_digitalizacao,
    listar_digitalizacoes,
    marcar_engano_digitalizacao,
    revisar_digitalizacao,
    trocar_paciente_digitalizacao,
    trocar_tipo_digitalizacao,
)
from .relatorio_atividade import (
    relatorio_atividade,
    relatorio_atividade_csv,
    relatorio_atividade_dia,
)
from .retificacoes import retificar_documento
from .views_whatsapp import (
    listar_lembretes_whatsapp,
    preparar_lembretes_amanha,
    simular_resposta_whatsapp,
    whatsapp_webhook,
)
from .prescricoes import listar_prescricoes, editar_prescricao, ver_prescricao, imprimir_prescricao
from .modo_simples import alternar_modo_simples
from .backup_arquivos import backup_arquivos
from .troca_senha import trocar_senha

urlpatterns = [
    path('pacientes/<int:paciente_pk>/exames/', include('exames.urls')),
    path('pacientes/<int:pk>/prescricoes/', listar_prescricoes, name='listar_prescricoes'),
    path('pacientes/<int:pk>/prescricoes/nova/', editar_prescricao, name='nova_prescricao'),
    path('pacientes/<int:pk>/prescricoes/<int:ficha_pk>/', ver_prescricao, name='ver_prescricao'),
    path('pacientes/<int:pk>/prescricoes/<int:ficha_pk>/editar/', editar_prescricao, name='editar_prescricao'),
    path('pacientes/<int:pk>/prescricoes/<int:ficha_pk>/imprimir/', imprimir_prescricao, name='imprimir_prescricao'),
    path('pacientes/<int:pk>/prescricoes/<int:ficha_pk>/pdf/', imprimir_prescricao, {'pdf': True}, name='pdf_prescricao'),
    path('documentos/<str:tipo>/<int:pk>/retificar/', retificar_documento, name='retificar_documento'),
    path('', inicio, name='inicio'),
    path('trocar-senha/', trocar_senha, name='trocar_senha'),
    path('modo-simples/', alternar_modo_simples, name='alternar_modo_simples'),
    path(
        'entradas-fora-do-horario/',
        listar_entradas_fora_do_horario,
        name='listar_entradas_fora_do_horario',
    ),
    path('digitalizacao/', listar_digitalizacoes, name='listar_digitalizacoes'),
    path('digitalizacao/nova/', digitalizacao_upload, name='digitalizacao_upload'),
    path(
        'digitalizacao/paciente/<int:pk>/',
        folhas_paciente,
        name='folhas_digitalizacao_paciente',
    ),
    path(
        'digitalizacao/paciente/<int:pk>/conferir/',
        conferir_folhas_paciente,
        name='conferir_folhas_digitalizacao',
    ),
    path(
        'digitalizacao/sem-paciente/',
        folhas_sem_paciente,
        name='folhas_digitalizacao_sem_paciente',
    ),
    path(
        'digitalizacao/sem-paciente/conferir/',
        conferir_folhas_sem_paciente,
        name='conferir_folhas_sem_paciente',
    ),
    path('digitalizacao/<int:pk>/', detalhe_digitalizacao, name='detalhe_digitalizacao'),
    path('digitalizacao/<int:pk>/foto/', foto_digitalizacao, name='foto_digitalizacao'),
    path('digitalizacao/<int:pk>/revisar/', revisar_digitalizacao, name='revisar_digitalizacao'),
    path('digitalizacao/<int:pk>/engano/', marcar_engano_digitalizacao, name='marcar_engano_digitalizacao'),
    path(
        'digitalizacao/<int:pk>/trocar-paciente/',
        trocar_paciente_digitalizacao,
        name='trocar_paciente_digitalizacao',
    ),
    path(
        'digitalizacao/<int:pk>/trocar-tipo/',
        trocar_tipo_digitalizacao,
        name='trocar_tipo_digitalizacao',
    ),
    path(
        'digitalizacao/<int:pk>/processar-ia/',
        digitalizacao_processar_ia,
        name='digitalizacao_processar_ia',
    ),
    path('administracao/', administracao, name='administracao'),
    path('administracao/copia-dos-arquivos/', backup_arquivos, name='backup_arquivos'),
    path('relatorio-atividade/', relatorio_atividade, name='relatorio_atividade'),
    path('relatorio-atividade/csv/', relatorio_atividade_csv, name='relatorio_atividade_csv'),
    path(
        'relatorio-atividade/<int:usuario_id>/<str:dia>/',
        relatorio_atividade_dia,
        name='relatorio_atividade_dia',
    ),
    path('financeiro/caixa/', caixa_diario, name='caixa_diario'),
    path('financeiro/caixa/abrir/', abrir_caixa, name='abrir_caixa'),
    path('financeiro/caixa/<int:pk>/movimento/', movimento_manual_caixa, name='movimento_manual_caixa'),
    path('financeiro/caixa/<int:pk>/fechar/', fechar_caixa, name='fechar_caixa'),
    path('financeiro/conciliacao/', listar_conciliacoes, name='listar_conciliacoes'),
    path('financeiro/conciliacao/origem/manual/', criar_importacao_extrato_manual, name='criar_importacao_extrato_manual'),
    path('financeiro/conciliacao/origem/<int:pk>/', detalhe_importacao_extrato, name='detalhe_importacao_extrato'),
    path('financeiro/conciliacao/origem/<int:pk>/lancamentos/manual/', criar_lancamento_extrato_manual, name='criar_lancamento_extrato_manual'),
    path('financeiro/conciliacao/lancamentos/<int:pk>/', conciliar_lancamento_extrato, name='conciliar_lancamento_extrato'),
    path('financeiro/conciliacao/<int:pk>/ajustes/', registrar_ajuste_conciliacao, name='registrar_ajuste_conciliacao'),
    path('financeiro/conciliacao/<int:pk>/cancelar/', cancelar_conciliacao, name='cancelar_conciliacao'),
    path('financeiro/formas-pagamento/', listar_formas_pagamento_configuraveis, name='listar_formas_pagamento_configuraveis'),
    path('financeiro/formas-pagamento/nova/', cadastrar_forma_pagamento_configuravel, name='cadastrar_forma_pagamento_configuravel'),
    path('financeiro/formas-pagamento/<int:pk>/editar/', editar_forma_pagamento_configuravel, name='editar_forma_pagamento_configuravel'),
    path('financeiro/relatorios/', relatorios_financeiros, name='relatorios_financeiros'),
    path('pacientes/', listar_pacientes, name='listar_pacientes'),
    path('pacientes/busca/', buscar_pacientes, name='buscar_pacientes'),
    path('pacientes/<int:pk>/ficha/', ficha_paciente, name='ficha_paciente'),
    path('pacientes/cadastrar/', cadastrar_paciente, name='cadastrar_paciente'),
    path('pacientes/<int:pk>/editar/', editar_paciente, name='editar_paciente'),
    path(
        'pacientes/<int:pk>/anamnese/',
        listar_fichas_anamnese,
        name='listar_fichas_anamnese',
    ),
    path(
        'pacientes/<int:pk>/anamnese/nova/',
        nova_ficha_anamnese,
        name='nova_ficha_anamnese',
    ),
    path(
        'pacientes/<int:pk>/anamnese/<int:ficha_pk>/link/',
        renovar_link_anamnese,
        name='renovar_link_anamnese',
    ),
    path(
        'pacientes/<int:pk>/anamnese/<int:ficha_pk>/editar/',
        editar_ficha_anamnese,
        name='editar_ficha_anamnese',
    ),
    path(
        'pacientes/<int:pk>/anamnese/<int:ficha_pk>/',
        ver_ficha_anamnese,
        name='ver_ficha_anamnese',
    ),
    path(
        'f/a/<uuid:token>/',
        ficha_anamnese_publica,
        name='ficha_anamnese_publica',
    ),
    path(
        'f/a/<uuid:token>/enviada/',
        ficha_anamnese_enviada,
        name='ficha_anamnese_enviada',
    ),
    path(
        'pacientes/<int:pk>/evolucao/',
        ficha_evolucao_clinica,
        name='ficha_evolucao_clinica',
    ),
    path(
        'pacientes/<int:pk>/plano/',
        listar_fichas_plano,
        name='listar_fichas_plano',
    ),
    path(
        'pacientes/<int:pk>/plano/novo/',
        nova_ficha_plano,
        name='nova_ficha_plano',
    ),
    path(
        'pacientes/<int:pk>/plano/<int:ficha_pk>/editar/',
        editar_ficha_plano,
        name='editar_ficha_plano',
    ),
    path(
        'pacientes/<int:pk>/plano/<int:ficha_pk>/',
        ver_ficha_plano,
        name='ver_ficha_plano',
    ),
    path(
        'pacientes/<int:pk>/autorizacao/',
        listar_fichas_autorizacao,
        name='listar_fichas_autorizacao',
    ),
    path(
        'pacientes/<int:pk>/autorizacao/novo/',
        nova_ficha_autorizacao,
        name='nova_ficha_autorizacao',
    ),
    path(
        'pacientes/<int:pk>/autorizacao/<int:ficha_pk>/editar/',
        editar_ficha_autorizacao,
        name='editar_ficha_autorizacao',
    ),
    path(
        'pacientes/<int:pk>/autorizacao/<int:ficha_pk>/',
        ver_ficha_autorizacao,
        name='ver_ficha_autorizacao',
    ),
    path('convenios/', listar_convenios, name='listar_convenios'),
    path('convenios/cadastrar/', cadastrar_convenio, name='cadastrar_convenio'),
    path('convenios/<int:pk>/editar/', editar_convenio, name='editar_convenio'),
    path(
        'convenios/uniodonto/tabela/',
        listar_tabela_uniodonto,
        name='listar_tabela_uniodonto',
    ),
    path(
        'convenios/uniodonto/repasses/',
        listar_repasses_uniodonto,
        name='listar_repasses_uniodonto',
    ),
    path(
        'convenios/uniodonto/repasses/novo/',
        cadastrar_repasse_uniodonto,
        name='cadastrar_repasse_uniodonto',
    ),
    path(
        'convenios/uniodonto/repasses/sugestao/',
        sugestao_producao_uniodonto,
        name='sugestao_producao_uniodonto',
    ),
    path(
        'convenios/uniodonto/repasses/<int:pk>/editar/',
        editar_repasse_uniodonto,
        name='editar_repasse_uniodonto',
    ),
    path('consultas/', listar_consultas, name='listar_consultas'),
    path('consultas/lembretes/', listar_lembretes_whatsapp, name='listar_lembretes_whatsapp'),
    path('consultas/lembretes/preparar/', preparar_lembretes_amanha, name='preparar_lembretes_amanha'),
    path(
        'consultas/lembretes/<int:pk>/simular/',
        simular_resposta_whatsapp,
        name='simular_resposta_whatsapp',
    ),
    path('whatsapp/webhook/', whatsapp_webhook, name='whatsapp_webhook'),
    path('consultas/agendar/', agendar_consulta, name='agendar_consulta'),
    path('consultas/horarios-ocupados/', horarios_ocupados, name='horarios_ocupados'),
    path('consultas/<int:pk>/remarcar/', remarcar_consulta, name='remarcar_consulta'),
    path('consultas/<int:pk>/', ficha_consulta, name='ficha_consulta'),
    path(
        'consultas/<int:pk>/autorizacao/novo/',
        nova_ficha_autorizacao_consulta,
        name='nova_ficha_autorizacao_consulta',
    ),
    path(
        'consultas/<int:pk>/status/',
        alterar_status_consulta,
        name='alterar_status_consulta',
    ),
    path(
        'consultas/<int:pk>/lancar/',
        lancar_atendimento,
        name='lancar_atendimento',
    ),
    path(
        'consultas/<int:pk>/dentista/',
        complementar_dentista,
        name='complementar_dentista',
    ),
    path('procedimentos/', listar_procedimentos, name='listar_procedimentos'),
    path(
        'procedimentos/cadastrar/',
        cadastrar_procedimento,
        name='cadastrar_procedimento',
    ),
    path(
        'procedimentos/<int:pk>/editar/',
        editar_procedimento,
        name='editar_procedimento',
    ),
    path(
        'consultas/pagamentos/',
        listar_pagamentos_consulta,
        name='listar_pagamentos_consulta',
    ),
    path(
        'consultas/materiais/',
        listar_materiais_dia,
        name='listar_materiais_dia',
    ),
    path(
        'consultas/<int:pk>/marcar-pago/',
        marcar_consulta_paga,
        name='marcar_consulta_paga',
    ),
    path(
        'consultas/<int:pk>/forma-pagamento/',
        salvar_forma_pagamento,
        name='salvar_forma_pagamento',
    ),
    path(
        'financeiro/contas-a-receber/',
        listar_contas_receber,
        name='listar_contas_receber',
    ),
    path(
        'financeiro/inadimplencia/',
        listar_inadimplencia,
        name='listar_inadimplencia',
    ),
    path('financeiro/fornecedores/', listar_fornecedores, name='listar_fornecedores'),
    path('financeiro/fornecedores/novo/', cadastrar_fornecedor, name='cadastrar_fornecedor'),
    path(
        'financeiro/categorias-contas-pagar/',
        listar_categorias_conta_pagar,
        name='listar_categorias_conta_pagar',
    ),
    path(
        'financeiro/categorias-contas-pagar/nova/',
        cadastrar_categoria_conta_pagar,
        name='cadastrar_categoria_conta_pagar',
    ),
    path('financeiro/contas-a-pagar/', listar_contas_pagar, name='listar_contas_pagar'),
    path('financeiro/contas-a-pagar/nova/', criar_conta_pagar, name='criar_conta_pagar'),
    path(
        'financeiro/contas-a-pagar/<int:pk>/',
        detalhe_conta_pagar,
        name='detalhe_conta_pagar',
    ),
    path(
        'financeiro/contas-a-pagar/<int:pk>/aprovar/',
        aprovar_conta_pagar,
        name='aprovar_conta_pagar',
    ),
    path(
        'financeiro/contas-a-pagar/<int:pk>/baixas/nova/',
        registrar_baixa_conta_pagar,
        name='registrar_baixa_conta_pagar',
    ),
    path(
        'financeiro/contas-a-receber/nova/',
        criar_conta_receber,
        name='criar_conta_receber',
    ),
    path(
        'financeiro/contas-a-receber/<int:pk>/',
        detalhe_conta_receber,
        name='detalhe_conta_receber',
    ),
    path(
        'financeiro/parcelas/<int:parcela_pk>/receber/',
        registrar_recebimento,
        name='registrar_recebimento',
    ),
    path(
        'financeiro/recebimentos/<int:pk>/estornar/',
        estornar_recebimento,
        name='estornar_recebimento',
    ),
    path(
        'financeiro/recebimentos/<int:pk>/recibo/',
        ver_recibo_recebimento,
        name='ver_recibo_recebimento',
    ),
    path(
        'consultas/<int:pk>/materiais/',
        materiais_consulta,
        name='materiais_consulta',
    ),
    path(
        'materiais/<int:pk>/editar/',
        editar_material_usado,
        name='editar_material_usado',
    ),
    path(
        'materiais/<int:pk>/excluir/',
        excluir_material_usado,
        name='excluir_material_usado',
    ),
    path(
        'fichas/assinatura/',
        teste_assinatura,
        name='teste_assinatura',
    ),
    path(
        'fichas/assinatura/<int:pk>/imagem/',
        ver_imagem_assinatura,
        name='ver_imagem_assinatura',
    ),
]
