# Generated by Django 6.1 on 2026-08-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('hora_inicio', models.TimeField(verbose_name='hora início')),
                ('hora_fim', models.TimeField(verbose_name='hora fim')),
                ('status', models.CharField(choices=[('disponivel', 'disponível'), ('reservada', 'reservada'), ('cancelada', 'cancelada')], default='disponivel', max_length=20, verbose_name='status')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disponibilidades', to='locacao.sala', verbose_name='sala')),
            ],
            options={
                'verbose_name': 'disponibilidade',
                'verbose_name_plural': 'disponibilidades',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
    ]
