# Generated by Django 6.1 on 2026-09-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0002_disponibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='nome completo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('sala', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dentista', to='locacao.sala', verbose_name='sala')),
            ],
            options={
                'verbose_name': 'dentista',
                'verbose_name_plural': 'dentistas',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mês (ex.: 01/09/2026 para setembro).', verbose_name='competência')),
                ('tipo', models.CharField(choices=[('geral', 'geral'), ('individual', 'individual')], max_length=20, verbose_name='tipo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('dentista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='locacao.dentista', verbose_name='dentista')),
            ],
            options={
                'verbose_name': 'despesa',
                'verbose_name_plural': 'despesas',
                'ordering': ['-competencia', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mês (ex.: 01/09/2026 para setembro).', verbose_name='competência')),
                ('pago', models.BooleanField(default=False, verbose_name='pago')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_mensais', to='locacao.dentista', verbose_name='dentista')),
            ],
            options={
                'verbose_name': 'pagamento mensal',
                'verbose_name_plural': 'pagamentos mensais',
                'ordering': ['-competencia', 'dentista'],
                'constraints': [models.UniqueConstraint(fields=('dentista', 'competencia'), name='pagamento_mensal_dentista_competencia_unico')],
            },
        ),
    ]
