# Generated by Django 6.1 on 2026-09-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0004_acerto_entre_dentistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentopar',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor líquido do acerto no momento em que foi marcado como pago.', max_digits=10, null=True, verbose_name='valor'),
        ),
    ]
