# Generated by Django 6.1 on 2026-09-05 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0005_pagamentopar_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('dentista', 'dentista'), ('auxiliar', 'auxiliar')], default='dentista', max_length=20, verbose_name='papel')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis', to='locacao.dentista', verbose_name='dentista')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil de usuário',
                'verbose_name_plural': 'perfis de usuário',
                'ordering': ['usuario__username'],
            },
        ),
    ]
