# Generated by Django 6.1 on 2026-09-05 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0006_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfis', to='locacao.dentista', verbose_name='dentista'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='papel',
            field=models.CharField(choices=[('dentista', 'dentista'), ('auxiliar', 'auxiliar'), ('secretaria', 'secretária')], default='dentista', max_length=20, verbose_name='papel'),
        ),
    ]
