# Generated by Django 6.1 on 2026-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0007_perfilusuario_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Usado só para sugerir preço de procedimento (valor-hora × duração estimada).', max_digits=10, verbose_name='valor-hora'),
        ),
    ]
