# Generated by Django 6.1 on 2026-09-11 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_contas_pagar_fornecedores'),
        ('locacao', '0008_procedimentos_lancamentos_legado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='conta_pagar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesa_rateio', to='core.contapagar', verbose_name='conta a pagar vinculada'),
        ),
        migrations.CreateModel(
            name='AuditoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='locacao.despesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
