# Generated by Django 6.1 on 2026-09-30 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0009_despesa_conta_pagar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'segunda-feira'), (1, 'terça-feira'), (2, 'quarta-feira'), (3, 'quinta-feira'), (4, 'sexta-feira'), (5, 'sábado'), (6, 'domingo')], verbose_name='dia da semana')),
                ('hora_inicio', models.TimeField(verbose_name='hora início')),
                ('hora_fim', models.TimeField(verbose_name='hora fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'turno de locação',
                'verbose_name_plural': 'turnos de locação',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='dentista',
            name='tipo',
            field=models.CharField(choices=[('titular', 'Titular'), ('locataria', 'Locatária de turnos')], default='titular', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='sala',
            field=models.OneToOneField(blank=True, help_text='Sala própria da titular. A locatária deixa este campo vazio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dentista', to='locacao.sala', verbose_name='sala'),
        ),
        migrations.AddConstraint(
            model_name='dentista',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sala__isnull', False), ('tipo', 'titular')), models.Q(('sala__isnull', True), ('tipo', 'locataria')), _connector='OR'), name='dentista_sala_conforme_tipo'),
        ),
        migrations.AddField(
            model_name='turnolocacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_locacao_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='turnolocacao',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='locacao.dentista', verbose_name='dentista'),
        ),
        migrations.AddField(
            model_name='turnolocacao',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_locacao', to='locacao.sala', verbose_name='sala'),
        ),
        migrations.AddIndex(
            model_name='turnolocacao',
            index=models.Index(fields=['sala', 'dia_semana', 'ativo'], name='turno_sala_dia_ativo'),
        ),
    ]
