# Generated by Django 6.1 on 2026-09-16 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0031_alter_digitalizacaoficha_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('foto', 'Fotografia clínica'), ('radiografia', 'Radiografia'), ('exame', 'Exame complementar'), ('laudo', 'Laudo')], max_length=20)),
                ('titulo', models.CharField(max_length=160)),
                ('data_exame', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, max_length=4000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chave', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tamanho', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=40)),
                ('sha256', models.CharField(max_length=64)),
                ('justificativa', models.CharField(blank=True, max_length=1000)),
                ('anterior', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substituto', to='exames.exame')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.consulta')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente')),
            ],
            options={
                'ordering': ['-criado_em'],
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='EventoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=40)),
                ('resultado', models.CharField(max_length=80)),
                ('justificativa', models.CharField(blank=True, max_length=1000)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('exame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='exames.exame')),
            ],
            options={
                'ordering': ['-pk'],
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='exame',
            constraint=models.CheckConstraint(condition=models.Q(('tamanho__gt', 0)), name='exame_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='eventoexame',
            constraint=models.UniqueConstraint(condition=models.Q(('acao__in', ['invalidado', 'substituido'])), fields=('exame',), name='exame_invalidacao_unica'),
        ),
    ]
