# Generated by Django 6.1 on 2026-09-09 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_fichaautorizacaocusto_arquivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimentoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(choices=[('transcricao_voz', 'Transcrição de voz do prontuário'), ('analise_imagem', 'Análise de imagem/radiografia'), ('rascunho_documento', 'Rascunho de documento'), ('outros', 'Outros')], max_length=30, verbose_name='Finalidade')),
                ('concedido', models.BooleanField(default=False, verbose_name='Concedido')),
                ('texto_versao', models.CharField(blank=True, max_length=20, verbose_name='Versão do termo')),
                ('concedido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concedido em')),
                ('revogado_em', models.DateTimeField(blank=True, null=True, verbose_name='Revogado em')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos_ia', to='core.paciente', verbose_name='Paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos_ia_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Consentimento de IA',
                'verbose_name_plural': 'Consentimentos de IA',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoriaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('recurso', models.CharField(choices=[('transcricao_voz', 'Transcrição de voz'), ('analise_imagem', 'Análise de imagem'), ('rascunho_documento', 'Rascunho de documento'), ('outros', 'Outros')], max_length=30, verbose_name='Recurso')),
                ('modelo_utilizado', models.CharField(blank=True, max_length=100, verbose_name='Modelo utilizado')),
                ('entrada_resumo', models.TextField(blank=True, verbose_name='Resumo da entrada')),
                ('saida_sugerida', models.TextField(blank=True, verbose_name='Saída sugerida pela IA')),
                ('decisao', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('editada', 'Editada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Decisão')),
                ('texto_final', models.TextField(blank=True, verbose_name='Texto final aprovado')),
                ('decidido_em', models.DateTimeField(blank=True, null=True, verbose_name='Decidido em')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_auditoria_ia', to='core.paciente', verbose_name='Paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_auditoria_ia', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de auditoria de IA',
                'verbose_name_plural': 'Registros de auditoria de IA',
                'ordering': ['-data_hora'],
            },
        ),
    ]
