# Generated by Django 6.1 on 2026-09-10 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fichaautorizacaocusto_arquivo'),
        ('ia_seguranca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoriaia',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_auditoria_ia', to='core.consulta', verbose_name='Consulta de origem'),
        ),
    ]
